[package]
name = "codewars"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "multiples_of_3_or_5_bench"
harness = false

[[bench]]
name = "vowel_count_bench"
harness = false

